### PR TITLE
some more routers setup -saifmohamed

### PR DESCRIPTION
**Pull request by saifmohamedsv**

### CODE REVIEW

**Comment by saifmohamedsv** [comment]
Please review and merge

**Comment by Ibrahim-Rezq** [comment]
2 things first routes are in app.jsx not main 😅 to separate routes and providers 
second resolve conflicts so I can merge I updated first by mistake 😬 😅

**Review by Ibrahim-Rezq — CHANGES_REQUESTED** [review]
2 things first routes are in app.jsx not main 😅 to separate routes and providers
second resolve conflicts so I can merge I updated first by mistake 😬 😅

**Comment by saifmohamedsv** [comment]
I don't understand where are the conflicts ?! ++ I didn't use react-router v6 if you mean that there is an issue in my router code

**Review by Ibrahim-Rezq — APPROVED** [review]

**Comment by Ibrahim-Rezq** [comment]
Pulled it to the main and merged from there

**Pull request closed without merging**
